### PR TITLE
adding transactions to add consensus nodes for DapperLabs

### PR DESCRIPTION
**Pull request by vishalchangrani**
DapperLabs will run 5 consensus nodes through Figment and eventually unstake 5 of their current consensus nodes.

### CODE REVIEW

**Review by joshuahannan — COMMENTED** [review]
Why is it in two transactions? Why can't it just be in one?

**Comment by vishalchangrani** [comment]
> Why is it in two transactions? Why can't it just be in one?

My understanding was that if the nodes are not staked but are added to the approved list of nodes, they get ejected out of the approved list as well. 
Please correct me if I am wrong and I will combine it into a single transaction.

**Comment by vishalchangrani** [comment]
adjusted the dates

**Review by joshuahannan — COMMENTED** [review]
I'm still confused why we are doing this with two transactions. If we have to add 5 nodes to the approved list, why can't we just do it in a single transaction?

**Pull request merged**
